authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
name = "SchumakerSpline"
uuid = "65e68595-3a03-5ff5-a6a2-f05fa774f32e"
version = "1.2.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
